### ISSUE TITLE
등록 기준

### ISSUE THREAD

**Issue by dittos** [dittos/wikistat#22]
문서 수가 너무 적은 위키도 등록해야 할지, 거른다면 하한선을 어느 정도로 둘지 정해야 합니다.

현재 하위 5개 위키 문서 수:

* 호토위키 (24)
* 버스위키 (550)
* 대한위키실록 (1460)
* 키위위키 (2957)
* 스레디키 (3643)

**Comment by CocoaWiki** [comment]
문서수 500개 이상이면 돼지 않을까요?
