### ISSUE TITLE
자유위키

### ISSUE THREAD

**Issue by 2DU** [dittos/wikistat#29]
```
---
id: jayuwiki
name: 자유위키
license: CC BY-NC-SA 4.0
url: "https://jayuwiki.miraheze.org/"
engine: mediawiki
engine_options:
  api_endpoint: "https://jayuwiki.miraheze.org/wiki/api.php"
```

위키에 추가 해달라고 글을 남겼더라고요 (깃허브 위키 이야깁니다)

**Comment by CocoaWiki** [comment]
<pre>
---
id: jayuwiki
name: 자유위키
license: CC BY-NC-SA 4.0
url: "https://jayuwiki.miraheze.org/"
engine: mediawiki
engine_options:
  api_endpoint: "https://jayuwiki.miraheze.org/w/api.php"
</pre>
이거 아닐까요 ㅇㅅㅇ

**Comment by CocoaWiki** [comment]
통계를 보니 전체문서가 500개를 넘긴 하네요. PR 넣을테니 이거 닫아주세요.
