### ISSUE TITLE
Wikistat에 '한국어 백괴게임' 추가 요청

### ISSUE THREAD

**Issue by trainroad** [dittos/wikistat#6]
http://game.uncyclopedia.kr : 대문
http://game.uncyclopedia.kr/wiki/%ED%8A%B9%EC%88%98:%EC%B5%9C%EA%B7%BC%EB%B0%94%EB%80%9C : 최근 바뀜
http://game.uncyclopedia.kr/wiki/%ED%8A%B9%EC%88%98:%ED%86%B5%EA%B3%84 : 통계

백괴사전의 자매 프로젝트로, Pull Request을 확인하지 않으시는 것 같아 이곳에 남겨 봅니다 :)

**Comment by dittos** [comment]
추가했습니다. 풀리퀘스트는 올라온 것을 확인하지 못했습니다.
